#!/bin/bash
killall -c mbbservice
#rm -rf /Library/StartupItems/MobileBrServ
rm -rf /Library/StartupItems/MobileBrServ/MobileBrServ
rm -rf /Library/StartupItems/MobileBrServ/SysConfig.dat
rm -rf /Library/StartupItems/MobileBrServ/StartupParameters.plist
rm -rf /Library/StartupItems/MobileBrServ/mbbservice
rm -rf /Library/StartupItems/MobileBrServ/mbbserviceUninstall.app
rm -rf /Library/StartupItems/MobileBrServ/runmbbserviceopen
rm -rf /Library/StartupItems/MobileBrServ/mbbserviceopen.app
rm -rf /Library/LaunchAgents/com.huawei.mbbservice.plist
rm -rf /tmp/mbbservice.pid
rm -rf /usr/local/FlashcardService/mbbservice.log
rm -rf \"/Applications/MobileWiFi.app\"

APP_NAME="MobileWiFi"
appspre=`defaults read $HOME/Library/Preferences/com.apple.dock persistent-apps`
nl=`echo "x" | tr 'x' '\34'`
appspost=`echo -n "$appspre" | sed "s/^[()]$//;s/},/}$nl/" | tr '\n\34' '\00\n'| grep -va "$APP_NAME" |tr '\n\00' ',\n' | sed 's/^,$//'`
sudo -u $USER defaults write com.apple.dock persistent-apps "($appspost)"

chmod a+w /usr
mkdir /usr/local

chmod 0440 /private/etc/sudoers

#echo $1 > /log.txt
#cp -Rf "${1}" /Library/StartupItems/MobileBrServ
installer -pkg "${1}" -target /
cp -Rf "${1}/../mbbserviceopen.app" "/Library/StartupItems/MobileBrServ/mbbserviceopen.app"
chown -R root:wheel /Library/StartupItems/MobileBrServ
chmod -R 755 /Library/StartupItems/MobileBrServ
chmod -R a+wrx /Library/StartupItems/MobileBrServ/mbbserviceopen.app
#open -a /Library/StartupItems/MobileBrServ/MobileBrServ &

